version: '3'

services:
    psql:
        image: postgres
        container_name: psql
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: spring_boots_demo
        volumes:
            - ./data/db/:/var/lib/postgresql/data
        ports:
            - '5432:5432'
